config/routes.rb
class SlugMatcher
  def initialize(klass)
    @klass = klass
  end

  def matches?(request)
    record = @klass.find_by_slug(request.params[:id])
    ! record.nil?
  end
end

class HierarchialSlugMatcher
  def initialize(klass)
    @klass = klass
  end

  def matches?(request)
    roots = @klass.roots
    parts = if request.params[:parent_id]
      [request.params[:parent_id], request.params[:id]]
    else
      request.params[:id].split('/')
    end

    for part in parts
      record = roots.find_by_slug(part)
      break if record.nil?
      roots = record.children
    end

    ! record.nil?
  end
end

Rails.application.routes.draw do
  themes_for_rails
  devise_for :users

  authenticate :user do
    mount RailsExceptionHandlerAdmin::Engine, :at => '/errors'
  end

  #devise_scope :user do
  #    get '/login' => 'devise/sessions#new'
  #    get '/logout' => 'devise/sessions#destroy'
  #end
  resources :user, :controller => "user"

  # TODO: use only in archive sidebar. See how made other system
  get ':year/:month', :to => 'articles#index', :year => /\d{4}/, :month => /\d{1,2}/, :as => 'articles_by_month', :format => false
  get ':year/:month/page/:page', :to => 'articles#index', :year => /\d{4}/, :month => /\d{1,2}/, :as => 'articles_by_month_page', :format => false
  get ':year', :to => 'articles#index', :year => /\d{4}/, :as => 'articles_by_year', :format => false
  get ':year/page/:page', :to => 'articles#index', :year => /\d{4}/, :as => 'articles_by_year_page', :format => false

  resources :dashboard, only: [:index], module: 'admin', path: '/admin'

  get 'articles.:format', to: 'articles#index', constraints: {:format => 'rss'}, as: 'rss'
  get 'articles.:format', to: 'articles#index', constraints: {:format => 'atom'}, as: 'atom'

  #scope :controller => 'xml', :path => 'xml', :as => 'xml' do
  #  get 'articlerss/:id/feed.xml', :action => 'articlerss', :format => false
  #end

  #get 'xml/:format', :to => 'xml#feed', :type => 'feed', :constraints => {:format => 'rss'}, :as => 'xml'
  #get 'sitemap.xml', :to => 'xml#feed', :format => 'googlesitemap', :type => 'sitemap', :as => 'xml'

  get 'sitemap.xml', to: 'xml#feed', format: 'googlesitemap', type: 'sitemap'

  # scope :controller => 'xml', :path => 'xml', :as => 'xml' do
  #   scope :action => 'feed' do
  #     get ':format/feed.xml', :type => 'feed'
  #     get ':format/:type/:id/feed.xml'
  #     get ':format/:type/feed.xml'
  #   end
  # end

  #get 'xml/rsd', :to => 'xml#rsd', :format => false
  get 'xml/feed', :to => 'xml#feed'

  # CommentsController
  # resources :comments, :as => 'admin_comments' do
  #   collection do
  #     get :preview
  #   end
  # end

  # ArticlesController
  get '/live_search/', :to => 'articles#live_search', :as => :live_search_articles, :format => false
  #get '/search/:q(.:format)/page/:page', :to => 'articles#search', :as => 'search'
  #get '/search(/:q(.:format))', :to => 'articles#search', :as => 'search'
  get '/search/', :to => 'articles#search', :as => :search_base, :format => false
  get '/archives/', :to => 'articles#archives', :format => false
  get '/page/:page', :to => 'articles#index', :page => /\d+/, :format => false
  get '/pages/*name', :to => 'articles#view_page', :format => false

  # CategoriesController (imitate inflected_resource)
  resources :themes, :except => [:show, :update, :destroy, :edit]
  resources :themes, :path => 'theme', :only => [:edit, :update, :destroy]

  get '*id/page/:page', to: 'themes#show', :format => false, :constraints => SlugMatcher.new(Theme)
  get '*id', to: 'themes#show', :format => false, :constraints => SlugMatcher.new(Theme)

  # TagsController (imitate inflected_resource)
  resources :tags, :except => [:show, :update, :destroy, :edit]
  resources :tags, :path => 'tag', :only => [:edit, :update, :destroy]
  get '/tags/page/:page', :to => 'tags#index', :format => false

  get '*id/page/:page', to: 'tags#show', :format => false, :constraints => SlugMatcher.new(Tag)
  get '*id', to: 'tags#show', :format => false, :constraints => SlugMatcher.new(Tag)

  get '*parent_id/*id', to: 'products#index', :format => false, :constraints => HierarchialSlugMatcher.new(ProductCategory)
  get '*id', to: 'products#index', :format => false, :constraints => HierarchialSlugMatcher.new(ProductCategory)

  get '*id', to: 'articles#view_page', :format => false, :constraints => SlugMatcher.new(Page)

  # AuthorsController
  #get '/author/:id(.:format)', :to => 'authors#show', :format => /rss|atom/, :as => 'xml'
  #get '/author(/:id)', :to => 'authors#show', :format => false
  #resources :authors

  # For the tests
  get 'theme/static_view_test', :format => false

  # Work around the Bad URI bug
  #%w{ files }.each do |i|
  #  get "#{i}", :to => "#{i}#index", :format => false
  #  get "#{i}(/:action)", :to => i, :format => false
  #  get "#{i}(/:action(/:id))", :to => i, :id => nil, :format => false
  #end

  resources :articles do
    get 'preview'
    get 'view_page'
    get 'recent', on: :collection
    get 'preview_page'
  end

  resources :products, :except => [:index, :show]
  match '/contact', to: 'contact#deliver', via: 'post'

  #unless Rails.configuration.poffy.products.url.nil?
  #  get Rails.configuration.poffy.products.url, :to => "products#index"
  #end
  get "*id" => "products#show", :constraints => SlugMatcher.new(Rails.configuration.poffy.products.model)

  namespace :admin do
    resources :articles do
      collection do
        post :autosave
      end
      #post :destroy, on: :member
      #get :auto_complete_for_article_keywords, on: :collection
#      get :attachment_box_add, on: :member
    end

    resources :blogs do
      collection do
        get :index
        get :integration
        get :display
        get :feedback
        get :seo
        get :titles
        get :slugs
        patch :update
      end
    end

    resources :resources do
      collection do
        get :get_thumbnails
        post :upload
        post :wysiwyg_upload
      end
    end

    resources :users
    resources :pages
    resources :products
    resources :redirects
    #resources :tags
    #resources :themes
    #resources :cache
    resources :post_types

    resources :tags do post :rebuild, on: :collection end
    resources :themes do post :rebuild, on: :collection end
    resources :product_categories do post :rebuild, on: :collection end
    resources :menus do post :rebuild, on: :collection end
  end

  # default
  root :to  => 'articles#index', :format => false

  unless Rails.configuration.poffy.pages.nil?
    get "*id" => "high_voltage/pages#show", :constraints => lambda{|req| Rails.configuration.poffy.pages.include?(req.params[:id]); }
  end

  get '*from', :to => 'articles#redirect', :format => false
end

app/models/article.rb
# coding: utf-8
require 'uri'
require 'net/http'

class Article < Content
  include PoffyGuid
  include ConfigManager
  include ActionView::Helpers::AssetTagHelper

  setting :linked_url, :string, title: "Linked URL", help: "An anchor of cover image. It's safe to leave empty"

  before_validation { process_settings(self.class) }

  validates_uniqueness_of :guid
  validates_presence_of :title
  validates_length_of :title, :maximum => 255
  #validates_presence_of :slug

  belongs_to :user
  belongs_to :resource

  has_and_belongs_to_many :themes, join_table: 'categorizations', association_foreign_key: 'category_id', :uniq => true
  has_and_belongs_to_many :tags, join_table: 'categorizations', association_foreign_key: 'category_id', :uniq => true

  #has_many :categorizations
  #has_many :themes, through: :categorizations
  accepts_nested_attributes_for :themes, :allow_destroy => true

  has_many :related_contents_association, :class_name => "RelatedContent"
  has_many :related_contents,
    through: :related_contents_association,
    source: :related_content

  has_many :triggers, as: :pending_item

  before_validation { process_settings(self.class) }
  before_create :create_guid
  before_save :set_published_at, :ensure_settings_type, :set_temporary_slug #, :set_permalink
  after_save :post_trigger, :shorten_url#, :keywords_to_tags

  #scope :category, lambda { |category_id| where('categorizations.category_id = ?', category_id).includes('categorizations') }
  scope :drafts, lambda { where(state: 'draft').order('created_at DESC') }
  scope :child_of, lambda { |article_id| where(parent_id: article_id) }
  scope :published_at, lambda {|time_params| published.where(published_at: PoffyTime.delta(*time_params)).order('published_at DESC')}
  scope :published_since, lambda {|time| published.where('published_at > ?', time) }
  scope :withdrawn, lambda { where(state: 'withdrawn').order('published_at DESC') }
  scope :pending, lambda { where('state = ? and published_at > ?', 'publication_pending', Time.now).order('published_at DESC') }
  scope :recent, -> () { where(["published = ?", true]).order('published_at DESC') }
  scope :bestof_week, ->() { published_since(DateTime.now - 7.days) }
  scope :bestof_month, ->() { published_since(DateTime.now - 30.days) }

  attr_accessor :draft, :keywords

  include Article::States

  has_state(:state,
    valid_states: [
      :new,
      :draft,
      :publication_pending,
      :just_published,
      :published,
      :just_withdrawn,
      :withdrawn
    ],
    initial_state: :new,
    :handles => [
      :withdraw,
      :post_trigger,
      :send_notifications,
      :published_at=,
      :just_published?
    ])


  #def set_permalink
  #  return if self.state == 'draft' || self.permalink.present?
  #  self.permalink = self.title.to_permalink
  #end

  def set_author(user)
    self.user = user
  end

  def has_child?
    Article.exists?(parent_id: self.id)
  end

  def post_type
    _post_type = read_attribute(:post_type)
    _post_type = 'read' if _post_type.blank?
    _post_type
  end

  def self.last_draft(article_id)
    article = Article.find(article_id)
    while article.has_child?
      article = Article.child_of(article.id).first
    end
    article
  end

  def self.search_with(params)
    params ||= {}
    scoped = super(params)
    if ["no_draft", "drafts", "published", "withdrawn", "pending"].include?(params[:state])
      scoped = scoped.send(params[:state])
    end

    if params[:category] && params[:category].to_i > 0
      scoped = scoped.category(params[:category])
    end

    scoped.order('created_at DESC')
  end

  def permalink_url(options = {})
    options[:only_path] = true if options[:only_path].nil?

    format_url = '/%slug%-post-%id%'
    format_url.gsub!('%id%', id.to_s)
    format_url.gsub!('%slug%', URI.encode(slug.to_s))

    if format_url[0,1] == '/'
      format_url = format_url[1..-1]
    end

    blog.url_for(format_url, options)
  end

  #def save_attachments!(files)
  #  files ||= {}
  #  files.values.each { |f| self.save_attachment!(f) }
  #end
  #
  #def save_attachment!(file)
  #  self.resources << Resource.create_and_upload(file)
  #rescue => e
  #  logger.info(e.message)
  #end

  # def feed_url(format)
  #   "#{permalink_url}.#{format.gsub(/\d/,'')}"
  # end

  def next
    Article.where('published_at > ?', published_at).order('published_at asc').limit(1).first
  end

  def previous
    Article.where('published_at < ?', published_at).order('published_at desc').limit(1).first
  end

  def self.find_by_published_at
    result = select('published_at').where('published_at is not NULL').where(type: 'Article')
    result.map{ |d| [d.published_at.strftime('%Y-%m')]}.uniq
  end

  # Finds one article which was posted on a certain date and matches the supplied dashed-title
  # params is a Hash
  def self.find_by_permalink(params)
    date_range = PoffyTime.delta(params[:year], params[:month], params[:day])

    req_params = {}
    req_params[:permalink] = params[:title] if params[:title]
    req_params[:published_at] = date_range if date_range

    return nil if req_params.empty? # no search if no params send
    article = find_published(:first, :conditions => req_params)
    return article if article

    if params[:title]
      req_params[:permalink] = CGI.escape(params[:title])
      article = find_published(:first, :conditions => req_params)
      return article if article
    end

    raise ActiveRecord::RecordNotFound
  end

  # Fulltext searches the body of published articles
  def self.search(query, args={})
    query_s = query.to_s.strip
    if !query_s.empty? && args.empty?
      Article.searchstring(query)
    elsif !query_s.empty? && !args.empty?
      Article.searchstring(query).page(args[:page]).per(args[:per])
    else
      []
    end
  end

  #def keywords_to_tags
  #  Tag.create_from_article!(self)
  #end

  def interested_users
    #User.find_all_by_notify_on_new_articles(true)
    User.where(notify_on_new_articles: true).all
  end

  def notify_user_via_email(user)
    if user.notify_via_email?
      EmailNotify.send_article(self, user)
    end
  end

  def comments_closed?
    ! allow_comments?
  end

  def html_urls
    urls = Array.new
    html.gsub(/<a\s+[^>]*>/) do |tag|
      if(tag =~ /\bhref=(["']?)([^ >"]+)\1/)
        urls.push($2.strip)
      end
    end
    urls.uniq
  end

  def cast_to_boolean(value)
    ActiveRecord::ConnectionAdapters::Column.value_to_boolean(value)
  end

  # Cast the input value for published= before passing it to the state.
  def published=(newval)
    state.published = cast_to_boolean(newval)
  end

  #def add_category(category, is_primary = false)
  #  self.categorizations.build(:category => category, :is_primary => is_primary)
  #end

  def access_by?(user)
    user.admin? || user_id == user.id
  end

  def allow_comments?
    return self.allow_comments unless self.allow_comments.nil?
    blog.default_allow_comments
  end

  protected

  def ensure_settings_type
    if settings.is_a?(String)
      # Any dump access forcing de-serialization
      true
    end
  end

  private

  def should_generate_new_friendly_id?
    super() && published?
  end

end

app/models/article/factory.rb
class Article::Factory

  attr_reader :blog, :user

  def initialize(blog, user)
    @blog, @user = blog, user
  end

  def default
    Article.new.tap do |art|
      art.allow_comments = blog.default_allow_comments
      art.user_id = @user.id
      art.published = true
    end
  end

  def get_or_build_from(id)
    return Article.find(id) if id.present?
    default
  end

  def match_permalink(url)
    re = /.*-post-(.*)/
    match = url.match re

    if match
      params = {}
      params[:id] = match[1]
      Article.published.where(params).first
    else
      return
    end
  end

  #def match_permalink_format(parts, format)
  #  specs = format.split('/')
  #  specs.delete('')
  #  parts = parts.split('/')
  #  parts.delete('')
  #
  #  return if parts.length != specs.length
  #
  #  article_params = {}
  #
  #  specs.zip(parts).each do |spec, item|
  #    if spec =~ /(.*)%(.*)%(.*)/
  #      before_format = $1
  #      format_string = $2
  #      after_format = $3
  #      result = item.gsub(/^#{before_format}(.*)#{after_format}$/, '\1')
  #      article_params[format_string.to_sym] = result
  #    elsif spec != item
  #      return
  #    end
  #  end
  #
  #  begin
  #    requested_article(article_params)
  #  rescue
  #    #Not really good.
  #    # TODO :Check in request_article type of DATA made in next step
  #  end
  #end
  #
  #def requested_article(params = {})
  #  params[:title] ||= params[:article_id]
  #  Article.find_by_permalink(params)
  #end

end

app/helpers/articles_helper.rb
require 'open-uri'
require 'json'
require 'active_support/dependencies'

module ArticlesHelper

  # usage:
  #   link_to_next_page(@items)
  #   link_to_next_page(@items, :remote => true)  # Ajax
  def link_to_next_page(scope, name, options = {}, html_options = {}, &block)
    param_name = options.delete(:param_name) || Kaminari.config.param_name
    link_to_unless scope.last_page?, name, options.merge(param_name => (scope.current_page + 1)), html_options.merge(:rel => 'next') do
      block.call if block
    end
  end

  def sidebar_recent_disussions(count)
    send(Rails.configuration.poffy.sidebar_recent_disussions, count)
  end

  def sidebar_recent_posts(count)
    send(Rails.configuration.poffy.sidebar_recent_posts, count)
  end

  # def recent_articles(count)
  #   Article.recent.page(1).per(count)
  # end

  # def similar_posts(article)
  #   Article
  #     .joins(:tags)
  #     .where('categorizations.id' => article.tags)
  #     .where.not(id: article)
  #     .order('published_at DESC')
  #     .group('contents.id')
  #     .take(4)
  # end

  # def best_posts
  #   articles = Article.bestof_week.by_popularity.take(3)
  #   articles = Article.bestof_month.by_popularity.take(3) if articles.count == 0
  #   articles
  # end

  def cover_url(article, size, with_placeholder=true)
    if article.resource
      '/' + article.resource.path(size)
    elsif with_placeholder
      current_theme_image_path('preview/post-' + size.to_s + '.gif')
    else
      nil
    end
  end

  def cover_img(article, size, options={})
    blog = Blog.default
    constraints = Resource.thumbnails_for('article')[size]

    options.reverse_merge! with_placeholder: true, alt: article.title, title: article.title, size: constraints

    url = cover_url(article, size, options[:with_placeholder])
    options.delete :with_placeholder

    if url
      image_tag url, options
    else
      nil
    end
  end
end

app/views/admin/articles/_article_list.html.erb
<%= render_void_table(@articles.size, 5) %>
<% for article in @articles %>
<tr>
  <td>
    <strong><%= link_to_edit h(article.title), article %></strong>
    <%= show_actions article %>
  </td>
  <td>
    <% if ! article.resource.nil? %>
      <%= cover_img article, :small, with_placeholder: true %><br />
    <% end %>
  </td>
  <td><%= article.themes.map { |c| link_to h(c.title), {:controller => 'articles', :action => 'index', "search[themes]" => c.id}}.join(", ").html_safe %></td>
  <td><%= article.user.username %></td>
  <td>
    <%= format_date article.published_at %><br />
    <%= published_or_not article %>
  </td>
</tr>
<% end %>
<%= display_pagination(@articles, 5, 'first', 'last')%>

app/views/admin/articles/_form.html.erb
<div class='row'>
  <h2 class='col-md-12 page-header'>
    <i class="fa fa-shopping-cart"></i>
    <%= "#{controller.action_name.to_s.capitalize} Article" %>

    <span class='pull-right'>
      <%= link_to('Cancel', {action: 'index'}, {class: 'btn btn-default'}) %>
      <span id='preview_link'>
        <%= link_to("Preview", article_preview_path(@article.id), {:target => 'new', :class => 'btn btn-default'}) if @article.id %>
      </span>
      <input id='save_draft' type="submit" value="Save as draft" name="article[draft]" class='btn btn-default' />

      <button class="btn btn-success">
        <%= controller.action_name == "new" ? "Publish" : "Save" %>
      </button>
    </span>
  </h2>
</div>

<div id="autosave"><%= set_autosave_tag(@article) %></div>

<div class='row'>
  <div class='col-md-8 col-md-offset-2' style='padding-top: 20px'>
    <%= error_messages_for @article %>
  </div>
</div>

<div class='row'>
  <div class="col-md-8">
    <%= f.text_field 'title', hide_label: :true, placeholder: 'Title' %>

    <div id="editor">
      <div id='simple_editor'>
        <%= f.tinymce_area 'body', hide_label: :true, rows: 20, cols: 120 %>
        <%= html_editor %>
      </div>
    </div>

    <%#= f.text_area :description %>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading"><h4 class="panel-title">Cover image</h4></div>

      <div class="panel-body">
        <% url = @article.resource.nil? ? '//:0' : '/' + @article.resource.path(:full) %>
        <%= f.hidden_field 'resource_id' %>

        <p id="preview_container">
          <a href="<%= url %>" rel="lazybox"><img src="<%= url %>" width="100%" id="preview_image"></a>
        </p>

        <p>
          <input type="button" id="choose_preview_button" value="Upload image" style="display:none" class="btn btn-primary pull-right">
          <input type="button" id="remove_preview_button" value="Remove image" style="display:none" class="btn btn-danger pull-right">
        </p>

        <script>
          toggle_preview(<%= @article.resource.nil? ? "false" : "true" %>);
        </script>

      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading"><h4 class="panel-title">Publish Settings</h4></div>

      <div class="panel-body">
        <%= f.collection_select :theme_ids, Theme.nested_set.all, :id, :title_with_path, { selected: @article.theme_ids, label: 'Themes' }, { multiple: true } %>
        <%= f.collection_select :tag_ids, Tag.nested_set.all, :id, :title_with_path, { selected: @article.tag_ids, label: 'Tags' }, { multiple: true } %>
        <%= f.collection_select :related_content_ids, this_blog.product_model.all, :id, :title, { selected: @article.related_content_ids, label: 'Products' }, { multiple: true } %>

        <script>
          $('#article_theme_ids').select2({ width: '100%' });
          $('#article_tag_ids').select2({ width: '100%' });
          $('#article_related_content_ids').select2({ width: '100%' });
        </script>

        <%= f.form_group do %>
          <p>
            Slug: <strong><%= @article.slug %></strong> <%= toggle_element('slug') %>
          </p>

          <div id='slug' class='collapse'>
            <%= f.text_field :slug, hide_label: :true, autocomplete: 'off' %>
          </div>
        <% end %>

        <%= f.form_group do %>
          <p>
            Status: <strong><%= @article.state.to_s.downcase %></strong> <%= toggle_element('status') %>
          </p>

          <div id='status' class='collapse'>
            <%= f.check_box :published, label: 'Published' %>
          </div>
        <% end %>

        <%= f.form_group do %>
          <p>
            User: <strong><%= @article.user.username %></strong> <%= toggle_element('user') %>
          </p>

          <div id='user' class='collapse'>
            <%= f.collection_select :user_id, User.all, :id, :username, selected: @article.user_id, hide_label: :true %>
          </div>
        <% end %>

        <%= f.form_group do %>
          <p>
            Comments are <%= content_tag(:strong, @article.allow_comments ? "enabled" : "disabled") %>
            <%= toggle_element('conversation') %>
          </p>

          <div id='conversation' class='collapse'>
            <%= f.check_box 'allow_comments', label: 'Allow comments' %>
          </div>
        <% end %>

        <%= f.form_group do %>
          <p>Published
            <strong>
              <%- if @article.published %>
                <%= display_date_and_time(@article.published_at) %>
              <%- else %>
                Now
              <%- end %>
            </strong>
            <%= toggle_element('publish') %>
          </p>
          <div id='publish' class='collapse'>
            <%= f.datetime_select 'published_at', { :"data-format" => "dd/MM/yyyy hh:mm:ss", use_month_numbers: true, hide_label: :true } %>
          </div>
        <% end %>
      </div>
    </div>
    <%= render :partial => "admin/shared/settings", locals: {f: f, instance: @article} %>
  </div>
</div>

app/views/admin/articles/edit.html.erb
<%= render :partial => "admin/shared/resource_upload", locals: {kind: 'article'} %>

<%= bootstrap_form_for @article,
  url: admin_article_path(@article.id),
  html: {
    id: "article_form",
    enctype: "multipart/form-data",
    class: 'autosave'
  } do |f| %>

  <%= render :partial => "form", locals: {f: f} %>

<% end %>

app/views/admin/articles/index.html.erb
<%- content_for :page_heading do %>
  <h2>
    <i class="fa fa-pencil"></i>
    Manage articles
    <%= link_to("New article", {controller: 'articles', action: 'new'}, id: 'dialog-link', class: 'btn btn-info pull-right')%>
  </h2>
<% end %>

<%= form_tag({action: 'index'}, {method: :get, name: 'article', remote: true, :class => 'form-inline spinnable', :"data-replace" => '#articleList'}) do %>

  <% if params[:search] and params[:search]['state'] %>
    <input type='hidden' name="search[state]" value="<%= params[:search]['state'] %>" >
  <% end %>
  
  <p>
    <%= link_to("All articles", {action: 'index'}, {class: 'label label-default'}) %>
    <%= link_to("Published", {action: 'index', search: {state: 'published'}}, {class: 'label label-success'}) %>
    <%= link_to("Withdrawn", {action: 'index', search: {state: 'withdrawn'}}, {class: 'label label-danger'}) %>
    <%= link_to("Drafts", {action: 'index', search: {state: 'drafts'}}, {class: 'label label-info'}) %>
    <%= link_to("Pending", {action: 'index', search: {state: 'pending'}}, {class: 'label label-warning'}) %>
  </p>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class='pull-right'>
        <div class='form-group'>
          <%= select_tag('search[user_id]',
                         options_from_collection_for_select(User.all, 'id', 'username', selected: (params[:search] and params[:search]['user_id'].present? ? params[:search]['user_id'] : nil)),
                         {prompt: "Select an author", class: 'form-control'}) %>
        </div>
        <div class='form-group'>
          <%= select_tag('search[published_at]',
                         options_for_select(Article.find_by_published_at, selected: (params[:search] and params[:search]['published_at'].present? ? params[:search]['published_at'] : nil)),
                         {prompt: "Publication date", class: 'form-control'}) %>
        </div>
        <div class='form-group'>
          <input id="search" type="text" name="search[searchstring]" class='form-control' value="<%= params[:search]['searchstring'] if params[:search] and params[:search]['searchstring'].present? %>"/>
        </div>
        <div class='form-group'>
          <%= submit_tag('Search', {:class => 'btn btn-success'}) %>
          <span id='spinner' style="display:none;"><%= image_tag('spinner.gif') %></span>                    
        </div>
      </div>
      <br style='clear: both' />
    </div>
  </div>
  <table class="table table-hover">
    <tbody id="articleList">
      <%= render 'article_list', { :articles => @articles } -%>
    </tbody>
  </table>
<%end%>

app/views/admin/articles/new.html.erb
<%= render :partial => "admin/shared/resource_upload", locals: {kind: 'article'} %>

<%= render "admin/shared/edit", {
  form_type: "article",
  form_action: { controller: :articles },
  form_method: :post,
  record: @article
} %>