config/routes.rb
class SlugMatcher
  def initialize(klass)
    @klass = klass
  end

  def matches?(request)
    record = @klass.find_by_slug(request.params[:id])
    ! record.nil?
  end
end

class HierarchialSlugMatcher
  def initialize(klass)
    @klass = klass
  end

  def matches?(request)
    roots = @klass.roots
    parts = if request.params[:parent_id]
      [request.params[:parent_id], request.params[:id]]
    else
      request.params[:id].split('/')
    end

    for part in parts
      record = roots.find_by_slug(part)
      break if record.nil?
      roots = record.children
    end

    ! record.nil?
  end
end

Rails.application.routes.draw do
  themes_for_rails
  devise_for :users

  authenticate :user do
    mount RailsExceptionHandlerAdmin::Engine, :at => '/errors'
  end

  #devise_scope :user do
  #    get '/login' => 'devise/sessions#new'
  #    get '/logout' => 'devise/sessions#destroy'
  #end
  resources :user, :controller => "user"

  # TODO: use only in archive sidebar. See how made other system
  get ':year/:month', :to => 'articles#index', :year => /\d{4}/, :month => /\d{1,2}/, :as => 'articles_by_month', :format => false
  get ':year/:month/page/:page', :to => 'articles#index', :year => /\d{4}/, :month => /\d{1,2}/, :as => 'articles_by_month_page', :format => false
  get ':year', :to => 'articles#index', :year => /\d{4}/, :as => 'articles_by_year', :format => false
  get ':year/page/:page', :to => 'articles#index', :year => /\d{4}/, :as => 'articles_by_year_page', :format => false

  resources :dashboard, only: [:index], module: 'admin', path: '/admin'

  get 'articles.:format', to: 'articles#index', constraints: {:format => 'rss'}, as: 'rss'
  get 'articles.:format', to: 'articles#index', constraints: {:format => 'atom'}, as: 'atom'

  #scope :controller => 'xml', :path => 'xml', :as => 'xml' do
  #  get 'articlerss/:id/feed.xml', :action => 'articlerss', :format => false
  #end

  #get 'xml/:format', :to => 'xml#feed', :type => 'feed', :constraints => {:format => 'rss'}, :as => 'xml'
  #get 'sitemap.xml', :to => 'xml#feed', :format => 'googlesitemap', :type => 'sitemap', :as => 'xml'

  get 'sitemap.xml', to: 'xml#feed', format: 'googlesitemap', type: 'sitemap'

  # scope :controller => 'xml', :path => 'xml', :as => 'xml' do
  #   scope :action => 'feed' do
  #     get ':format/feed.xml', :type => 'feed'
  #     get ':format/:type/:id/feed.xml'
  #     get ':format/:type/feed.xml'
  #   end
  # end

  #get 'xml/rsd', :to => 'xml#rsd', :format => false
  get 'xml/feed', :to => 'xml#feed'

  # CommentsController
  # resources :comments, :as => 'admin_comments' do
  #   collection do
  #     get :preview
  #   end
  # end

  # ArticlesController
  get '/live_search/', :to => 'articles#live_search', :as => :live_search_articles, :format => false
  #get '/search/:q(.:format)/page/:page', :to => 'articles#search', :as => 'search'
  #get '/search(/:q(.:format))', :to => 'articles#search', :as => 'search'
  get '/search/', :to => 'articles#search', :as => :search_base, :format => false
  get '/archives/', :to => 'articles#archives', :format => false
  get '/page/:page', :to => 'articles#index', :page => /\d+/, :format => false
  get '/pages/*name', :to => 'articles#view_page', :format => false

  # CategoriesController (imitate inflected_resource)
  resources :themes, :except => [:show, :update, :destroy, :edit]
  resources :themes, :path => 'theme', :only => [:edit, :update, :destroy]

  get '*id/page/:page', to: 'themes#show', :format => false, :constraints => SlugMatcher.new(Theme)
  get '*id', to: 'themes#show', :format => false, :constraints => SlugMatcher.new(Theme)

  # TagsController (imitate inflected_resource)
  resources :tags, :except => [:show, :update, :destroy, :edit]
  resources :tags, :path => 'tag', :only => [:edit, :update, :destroy]
  get '/tags/page/:page', :to => 'tags#index', :format => false

  get '*id/page/:page', to: 'tags#show', :format => false, :constraints => SlugMatcher.new(Tag)
  get '*id', to: 'tags#show', :format => false, :constraints => SlugMatcher.new(Tag)

  get '*parent_id/*id', to: 'products#index', :format => false, :constraints => HierarchialSlugMatcher.new(ProductCategory)
  get '*id', to: 'products#index', :format => false, :constraints => HierarchialSlugMatcher.new(ProductCategory)

  get '*id', to: 'articles#view_page', :format => false, :constraints => SlugMatcher.new(Page)

  # AuthorsController
  #get '/author/:id(.:format)', :to => 'authors#show', :format => /rss|atom/, :as => 'xml'
  #get '/author(/:id)', :to => 'authors#show', :format => false
  #resources :authors

  # For the tests
  get 'theme/static_view_test', :format => false

  # Work around the Bad URI bug
  #%w{ files }.each do |i|
  #  get "#{i}", :to => "#{i}#index", :format => false
  #  get "#{i}(/:action)", :to => i, :format => false
  #  get "#{i}(/:action(/:id))", :to => i, :id => nil, :format => false
  #end

  resources :articles do
    get 'preview'
    get 'view_page'
    get 'recent', on: :collection
    get 'preview_page'
  end

  resources :products, :except => [:index, :show]
  match '/contact', to: 'contact#deliver', via: 'post'

  #unless Rails.configuration.poffy.products.url.nil?
  #  get Rails.configuration.poffy.products.url, :to => "products#index"
  #end
  get "*id" => "products#show", :constraints => SlugMatcher.new(Rails.configuration.poffy.products.model)

  namespace :admin do
    resources :articles do
      collection do
        post :autosave
      end
      #post :destroy, on: :member
      #get :auto_complete_for_article_keywords, on: :collection
#      get :attachment_box_add, on: :member
    end

    resources :blogs do
      collection do
        get :index
        get :integration
        get :display
        get :feedback
        get :seo
        get :titles
        get :slugs
        patch :update
      end
    end

    resources :resources do
      collection do
        get :get_thumbnails
        post :upload
        post :wysiwyg_upload
      end
    end

    resources :users
    resources :pages
    resources :products
    resources :redirects
    #resources :tags
    #resources :themes
    #resources :cache
    resources :post_types

    resources :tags do post :rebuild, on: :collection end
    resources :themes do post :rebuild, on: :collection end
    resources :product_categories do post :rebuild, on: :collection end
    resources :menus do post :rebuild, on: :collection end
  end

  # default
  root :to  => 'articles#index', :format => false

  unless Rails.configuration.poffy.pages.nil?
    get "*id" => "high_voltage/pages#show", :constraints => lambda{|req| Rails.configuration.poffy.pages.include?(req.params[:id]); }
  end

  get '*from', :to => 'articles#redirect', :format => false
end

app/models/product.rb
class Product < Content
  include PoffyGuid
  include ConfigManager

  belongs_to :user
  belongs_to :resource

  setting :linked_url, :string, title: "Linked URL", help: "2 An anchor of cover image. It's safe to leave empty"
  setting :shortname, :string
  setting :icon, :image
  # setting :url, :string
  setting :prio, :integer
  setting :rating, :integer
  setting :header_top, :string
  setting :header_middle, :text
  setting :button_label, :string, help: "Product list page. If empty -- no button will be shown", title: "Product list button"
  setting :main_button_label, :string, help: "On product page is the Big Red Button over the heading image"
  setting :bottom_button_label, :string, help: "On product page is the Big Green Button on the bottom"

  before_validation { process_settings(self.class) }

  before_create :create_guid
  before_save :set_published_at, :set_temporary_slug

  after_save :shorten_url

  validates_presence_of :title, :shortname
  validates_length_of :title, :maximum => 255

  has_and_belongs_to_many :product_categories, join_table: 'categorizations', association_foreign_key: 'category_id', foreign_key: 'article_id'

  has_many :related_articles_association, :class_name => "RelatedContent", :foreign_key => "related_content_id"
  has_many :related_articles, :through => :related_articles_association, :source => :article

  def self.default_order
    "settings -> 'prio' ASC"
  end

  def self.init_url_helpers(klass)
    self.fields_for_merged(klass).each_value do |item|
      case item.ruby_type
        when :image
          define_method("#{item.name}_url") do
            value = self.send(item.name)
            "/files/product/#{value}" unless value.nil?
          end
      end
    end
  end

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterate: Rails.configuration.poffy.transliteration.to_sym).to_s
  end

  def permalink_url
    blog = Blog.default # remove me...
    blog.url_for(controller: 'products', action: 'show', id: if slug.to_s == "" then id else slug end, only_path: true)
  end

  def should_generate_new_friendly_id?
    new_record? || slug.blank?
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  skip_load_and_authorize_resource

  layout "administration", :except => 'show'

  def index
    @search = params[:search] ? params[:search] : {}
    @products = this_blog.product_model
      .search_with(@search)
      .page(params[:page])
      .per(this_blog.admin_display_elements)
  end

  def new
    @product = this_blog.product_model.new(params[:product])
    @product.user_id = current_user.id
  end

  def edit
    @product = this_blog.product_model.find(params[:id])
  end

  def create
    @product = this_blog.product_model.new(resource_params)
    @product.user_id = current_user.id

    @product.published_at = Time.now

    if @product.save
      flash[:notice] = 'Product was successfully created.'
      redirect_to :action => 'index'
    else
      flash[:notice] = @product.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def update
    @product = this_blog.product_model.find(params[:id])
    @product.attributes = resource_params
    if @product.save
      flash[:notice] = 'Product was successfully updated.'
      redirect_to :action => 'index'
    else
      flash[:notice] = @product.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  def destroy
    destroy_a(this_blog.product_model)
  end

  private

  def resource_params
    params.require(this_blog.product_model.name.underscore).permit(
      :title,
      :slug,
      :body,
      :description,
      :resource_id,
      :published,
      *this_blog.product_model.fields_for_merged_self.keys,
      :product_category_ids => [],
      :_removed_images => [],
      :_prev_images => []
    )
  end

end

app/controllers/products_controller.rb
class ProductsController < ContentController

  def index
    @product_category = ProductCategory.friendly.find(params[:id])

    if @product_category.nil?
      render "errors/404", status: 404
    else
      parent_products = this_blog.product_model
        .joins(:product_categories)
        .where('categories.id' => @product_category.id)
        .order("contents.settings -> 'prio' ASC").published.all

      child_products = this_blog.product_model
        .joins(:product_categories)
        .where('categories.id' => @product_category.children.collect(&:id))
        .order("contents.settings -> 'prio' ASC").published.all

      @products = parent_products + child_products

      @subcategories = if @product_category.root.nil?
                         @product_category.children
                       else
                         @product_category.root.children
                       end

      @page_title = this_blog.products_list_title_template
      @description = this_blog.products_list_desc_template

      @page_title = @page_title.to_title(@product_category, this_blog, params)
      @description = @description.to_title(@product_category, this_blog, params)
    end
  end

  def show
    if (@product = this_blog.product_model.friendly.find(params[:id])) && @product.published?
      @page_title = this_blog.product_title_template
      # @description = this_blog.products_list_desc_template

      @page_title = @page_title.to_title(@product, this_blog, params)

      @meta_description = @product.meta_description

      # @description = @description.to_title(@product, this_blog, params)
    else
      render "errors/404", status: 404
    end

  end

end

app/views/products/_product.html.erb
<article class="product room">
  <a href="<%= product.permalink_url %>">
    <% if ! product.icon.nil? && ! product.icon.empty? %>
      <img src="<%= product.icon_url %>" alt="<%= product.title %>" />
    <% end %>
  </a>

  <h3>
    <%= link_to product.shortname, product.permalink_url %>
  </h3>

  <% unless product.product_categories.collect(&:id).include? @product_category.id then %>
    <i><%= product.product_categories[0].title %></i>
  <% end %>

  <% if product.rating.to_i > 0 %>
    <span class="rating">
      <% 1.upto(5).each do |rating| %>
        <i<% if product.rating.to_i >= rating %> class="selected"<% end -%>></i>
      <% end -%>
    </span>
  <% end %>

  <% if product.button_label.present? %>
    <%= link_to product.button_label, product.permalink_url, class: "button" %>
  <% end %>

</article>

app/views/products/index.html.erb
<div id="content" class="page-products">
  <% have_aside = (@subcategories.size > 0 and @subcategories.collect(&:slug).reject(&:empty?).size > 0) %>
  <div class="sections-group <%= if have_aside then 'content-left' end %>">
    <section class="products-collection">
      <h1><%= @product_category.title %></h1>
      <p>
          <%= @product_category.body.html_safe %>
          <br/><br/>
      </p>

      <ul id="products-grid-section" class="grid grid-col-<%= have_aside ? '3' : '4' %> products-grid">
        <% @products.each do |product| -%>
          <li>
              <%= render :partial => 'product', locals: { product: product } %>
          </li>
        <% end -%>
      </ul>
    </section>
  </div>

  <style>
    .bold {
      font-weight: bold;
    }
  </style>

  <% if have_aside %>
    <aside>
      <section class="panel panel-nav grey-bg">
        <header><h2><%= t('.categories') %></h2></header>
        <nav>
          <ul class="list">
            <% top_category = if @product_category.parent.nil? then @product_category else @product_category.parent end %>
            <li><a href="<%= top_category.permalink_url %>" class="<% if @product_category.parent.nil? %>bold<% end %>"><%= t('.all') %></a></li>
            <% @subcategories.each do |c| %>
              <li><%= link_to c.title, c.permalink_url, class: @product_category.id == c.id ? 'bold' : '' %></li>
            <% end %>
          </ul>
        </nav>
      </section>
    </aside>
  <% end %>

</div>

app/views/products/show.html.erb
<div id="content" class="room-page" itemscope itemtype="http://schema.org/Article">
  <meta itemprop="name" content="<%= @product.title %>" />
  <meta itemprop="url" content="<%= product_url(@product.id) %>" />

  <article class="product">
    <h1><%= @product.title %></h1>

    <header>
      <figure class="product-default">
        <img src="<%= if @product.resource then cover_url(@product, :full, false) end %>" alt="<%= @product.title %>" />
        <figcaption>
          <a class="product-link" href="<%= @product.linked_url %>"></a>
          <div class="product-title"><%= @product.header_top.html_safe %></div>
          <div class="product-description"><%= @product.header_middle.html_safe %></div>
          <a class="button button-download product-download" href="<%= @product.linked_url %>" target="_blank">
            <span><%= @product.main_button_label.presence || t(".red_button") %></span>
            <i><%= Addressable::URI.parse(@product.linked_url).host %></i>
          </a>
        </figcaption>
      </figure>
    </header>

    <div class="sections-group content-left">
      <section>
        <div class="ww-text">
          <%= @product.body.html_safe %>
        </div>
      </section>

      <section>
        <p class="center">
          <a href="<%= @product.linked_url %>" class="button button-download" target="_blank"><i></i><%= @product.bottom_button_label.presence || t(".bottom_button", {label: @product.shortname}) %></a>
        </p>
      </section>
    </div>

    <aside>
      <% if @product.respond_to?(:screenshot_small) &&
              ! @product.screenshot_small.nil? &&
              ! @product.screenshot_small.empty? %>
        <section class="product-screenshots">
           <img src="<%= @product.screenshot_small_url %>" alt="<%= @product.title %>">
        </section>
      <% end -%>

      <section class="panel grey-bg feedbacks-collection raiting">
        <div id="create-feedback" itemscope itemtype="http://schema.org/AggregateRating" itemprop="aggregateRating">
          <span itemprop="ratingValue"><%= number_with_precision(@product.rating.to_i, precision: 1, delimiter: ',') %></span>
          <meta itemprop="worstRating" content="1"/>
          <meta itemprop="bestRating" content="5"/>
          <meta itemprop="ratingCount" content="1"/>

          <ul id="product-rater" class="stars">
            <% (1..5).each do |value| %>
              <li<%= ' class=empty' if value > @product.rating.to_i %> <% 'itemprop="ratingValue"' if value == @product.rating.to_i %>><%= value -%></li>
            <% end %>
          </ul>
          <i></i>
        </div>
      </section>

      <% if @product.related_articles.count > 0 %>
        <%= widget('aside', @product) %>
      <% end %>
    </aside>

  </article>

</div>